apiVersion: batch/v1
kind: Job
metadata:
  name: stock-crawler-job
spec:
  template:
    spec:
      containers:
      - name: stock-crawler
        image: fabricioveronez/stock-crawler:v1
        imagePullPolicy: Always
        env:
          - name: MONGODB_URL
            value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
          - name: PAGE_URL
            value: http://web-stock-service:80
      restartPolicy: Never
  backoffLimit: 4